export const AUTH_INIT = 'AUTH_INIT';
export const SET_USERDATA = 'SET_USERDATA';
export const SET_ERROR = 'SET_ERROR';
export const SET_USERNAME = 'SET_USERNAME';
export const FETCH_USERNAME = 'FETCH_USERNAME';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const AUTO_LOGIN = 'AUTO_LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SHOW_ERROR_MODAL = 'SHOW_ERROR_MODAL';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS = 'FETCH_CONVERSATIONS';
export const FETCH_CONVERSATIONS_INIT = 'FETCH_CONVERSATIONS_INIT';
export const FETCH_CONVERSATIONS_FAILED = 'FETCH_CONVERSATIONS_FAILED';
export const SET_CONVERSATIONS = 'SET_CONVERSATIONS';

export const SET_CONVO = 'FETCH_CONVO';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_INIT = 'SEND_MESSAGE_INIT';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';